Implemented function for generating list of people in contact with an infected person
AY2021S1-CS2103T-T13-1/tp pull request #134
Opened 2020-10-10 12:12 UTC by KohHanMing

Implemented function for generating list of people in contact with an infected person and included tests as well.

2020-10-10 14:21 UTC, DreamerDragon approved these changes
LGTM

2020-10-10 14:37 UTC, hopinxian requested changes

2020-10-10 14:37 UTC, hopinxian commented on src/main/java/seedu/address/logic/commands/CommandUtil.java
> +    }
Could this perhaps be shifted to info handler class? This can help to keep calculation and information handling methods consolidated in one place.

2020-10-10 14:37 UTC, hopinxian commented on src/main/java/seedu/address/logic/commands/GeneratePeopleCommand.java
> +    }
This code is quite long. May I suggest extracting part of it into another method? This is a suggestion in accordance to single line of abstraction.

2020-10-10 14:37 UTC, hopinxian commented on src/test/java/seedu/address/logic/commands/GenerateLocationsCommandTest.java
> +}
You have added tests capturing failing conditions. May I suggest tests that confirm success conditions as well?

2020-10-11 02:32 UTC, hopinxian commented
Suggest to merge visit id fix PR first #136 and see if any of the tests crash for this particular PR.

2020-10-11 04:37 UTC, hopinxian approved these changes
LGTM

2020-10-11 04:37 UTC, merged