Adapt User Guide to VirusTracker
AY2021S1-CS2103T-T13-1/tp pull request #86
Opened 2020-09-28 08:08 UTC by siangernlow

Close #85

2020-09-28 12:54 UTC, KohHanMing approved these changes
Other than the list people command, everything looks good :)

2020-09-29 07:03 UTC, hopinxian requested changes
LGTM after minor changes.

2020-09-29 07:03 UTC, hopinxian commented on docs/UserGuide.md
> +**List** | `list l/KEYWORD` <br> e.g., `list people`, `list stats`
I think that to match prefix, the e.g. would be sth like list l/people, list /stats. Please check on this.

2020-09-29 07:03 UTC, hopinxian commented on docs/UserGuide.md
> +AddressBook data saves in the hard disk automatically after any command that changes the data. There is no need to save manually.
Might want to refer to this as Virus Tracker instead of AddressBook.

2020-09-29 07:03 UTC, hopinxian commented on docs/UserGuide.md
> +Clears all entries in the current list view from VirusTracker.
Might consider changing to 'Clears all entries from Virus Tracker' to match description in line 42.

2020-09-29 08:34 UTC, hopinxian approved these changes
LGTM

2020-09-29 08:34 UTC, merged